### ISSUE TITLE
Bower can't find ngDraggable

### ISSUE THREAD

**Issue by vinilanzoni** [fatlinesofcode/ngDraggable#100]
When I run ```bower update``` / ```bower install``` is shown this: ```Package ngDraggable not found```.
I saw that the package was renamed to lowercase and back to the old name. And I already tried to rename the package name to lowercase and back to the old name and the bower is still breaking.

**Comment by praneetkinnser** [comment]
Its the same for me.

**Comment by fatlinesofcode** [comment]
try 
bower cache clean
bower install ngdraggable --save

**Comment by praneetkinnser** [comment]
Sorry, that didn't work. Still the same issue.
Package ngDraggable not found

**Comment by vinilanzoni** [comment]
It worked for me. I just did another command:
```bower uninstall ngDraggable --save```
then 
```bower cache clean```
```bower install ngdraggable --save```

**Comment by fatlinesofcode** [comment]
its pretty annoying, ill ask bower support if they'll register a 'ngDraggable' alias

**Comment by fatlinesofcode** [comment]
bower team renamed the package back to 'ngDraggable'

**Comment by DShumkov** [comment]
README.md needs to be updated. There is wrong name in the example of package installation. Should be - 'bower install ngDraggable'

**Comment by fatlinesofcode** [comment]
its already been updated

**Comment by DShumkov** [comment]
Oops sorry. You are so fast :)

**Comment by praneetkinnser** [comment]
Yup.. works now.. Thanks!
