### ISSUE TITLE
ngDraggable Without the log

### ISSUE THREAD

**Issue by allbto2** [fatlinesofcode/ngDraggable#102]
Hey,

I'm using ngDraggable for a project of my company.
First I would like to thank you it's really great and fits perfectly with what I need.

My only problem though is that I want to put my website to production but there is a lot of log coming from ngDraggable and since I'm using bower, I can't manually remove them.

Is there a way to bi-pass that ? Or maybe just adding an option to remove log would do it.

Thanks a lot !

**Comment by imcnally** [comment]
:+1:

**Comment by jkarttunen** [comment]
I'm sure this will be closed soon, but meanwhile you can do

"ngDraggable": "git@github.com:jkarttunen/ngDraggable.git#352dc449893c2c72e74373100428ed27c0623c5a",

**Comment by allbto2** [comment]
Thanks !

**Comment by imcnally** [comment]
Added ability to turn logging on & off in #105. Waiting on feedback.

**Comment by fatlinesofcode** [comment]
fixed in 0.1.3
