### ISSUE TITLE
Items not dragging properly

### ISSUE THREAD

**Issue by imcnally** [fatlinesofcode/ngDraggable#103]
Hey Philip,

I noticed dragging didn't work the same, when the change from pixels to matrix3d transforms was made (so, 0.0.3.1 works, but 0.0.4 doesn't).

The older, working version:
![](http://media.tumblr.com/3f2dd458d4d08f92c2547b1cca697149/tumblr_inline_nkt3bj2kxL1sssr44.gif)

The lastest version:
![2015-03-16 16_34_59](https://cloud.githubusercontent.com/assets/1494758/6675911/6fd36672-cbfa-11e4-9787-54916ffba459.gif)

 I tried seeing what the motivation was for the change (#74), but couldn't get a clear picture of it. Any ideas on how to proceed?

**Comment by imcnally** [comment]
cc @janober

**Comment by ohho** [comment]
:+1:

**Comment by imcnally** [comment]
One idea I had was to have the way it drags configurable, since it seems like there are a few use cases for dragging. Similar to what I did in #105 for debug logging, we could have a configuration option to drag in pixels, or to do a transform. In that case, the `ngDraggable` provider could return the CSS for movement, depending on which method was chosen.

**Comment by fatlinesofcode** [comment]
@imcnally your issue looks like a simple CSS issue. Try setting the z-index on your dragging element or maybe set it to fixed.
Additional there is already an option of disabling transform movement. data-allow-transform="false"

**Comment by janober** [comment]
Uh sorry for the issues! Does the solution from above work?

The reason I made the change was that before it broke (the item had an offset) when a parent element had a matrix3d transform on it which for example famo.us uses a lot.

**Comment by imcnally** [comment]
@fatlinesofcode z-index is set to 999999 by the drag directive, so manually setting it did nothing. By "set it to fixed", do you mean position: fixed?

Also, disabling the transform didn't help. The draggable item simply disappears when I click on it.

**Comment by jkarttunen** [comment]
+1

**Comment by fatlinesofcode** [comment]
Do you have a fiddle example?

**Comment by imcnally** [comment]
I tried making one but couldn't replicate the issue. I'll keep trying.

**Comment by jkarttunen** [comment]
Looks like removing overflow: auto from direct parent helps on my case

**Comment by jkarttunen** [comment]
Okies, seems like this is of course expected browser behaviour, CSS transforms should not be drawn outside container with overflow:hidden.

**Comment by imcnally** [comment]
@jkarttunen you were right about overflow: auto. Demo here: http://codepen.io/imcnally/pen/ByvaeK

**Comment by jkarttunen** [comment]
Not sure how to fix this other than using position : fixed and coordinates instead transform ... :/

**Comment by jkarttunen** [comment]
using data-allow-transform="false" fixes this. 
Lets add that to the readme, pretty please.

**Comment by imcnally** [comment]
I tried allow-transform on the [pen](http://codepen.io/imcnally/pen/ByvaeK) and it throws off position on other elements.

**Comment by jkarttunen** [comment]
@imcnally Not sure what you mean by 'throws off position on other elements' ?

**Comment by imcnally** [comment]
If you start dragging them item in the example I posted, you'll notice the
drop area shifting down while dragging.

On Wed, Mar 18, 2015 at 7:18 PM, Juha Karttunen <notifications@github.com>
wrote:

> @imcnally <https://github.com/imcnally> Not sure what you mean by 'throws
> off position on other elements' ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fatlinesofcode/ngDraggable/issues/103#issuecomment-83221364>
> .
>



-- 
best,
Ian

**Comment by jkarttunen** [comment]
On Safari yes, not on Chrome or FF.

**Comment by janober** [comment]
I guess rolling back is best. Does not seem like there is an easy and good solution. Also nobody else seems to use "matrix3d transform" anyway. So rolling back my change makes the most sense.

**Comment by josephlavin** [comment]
Are you using bootstrap?  If so I had a similar issues regarding rows and columns an was able to overcome it by adding css `position: relative;` on the dragging element.

~~~css
[ng-drag].dragging {
  position: relative;
}
~~~

**Comment by djak250** [comment]
Thanks @josephlavin. That fixed my issue with it hiding behind a bootstrap column.

**Comment by amuste** [comment]
Just add position absolute to the dragging object 
 
 [ng-drag].dragging {
                         position: absolute;
                       }

**Comment by esfandani** [comment]
I have the same problem. Does anybody know how to solve this?

**Comment by dbounds** [comment]
@amuste that didn't solve the issue for me.

position: absolute didn't resolve this for me. I've heard the same from others I've spoken to about this.

transform3D doesn't abide by z-index.

**Comment by amuste** [comment]
@dbounds  See the plunker 
http://plnkr.co/edit/bWQ7JEei3O5AIr2tW1g9?p=preview

in style.cs find .listbox-content > ul > li.dragging {} and remove 
"position: absolute ". to see the result behaviour.

**Comment by ricardofilho6** [comment]
I have the same issue with angular-bootstrap-calendar, the element hides it itself when dragging to other view or scroll div. I tried ngDraggable but it didn't work either. None of the solutions above helped me =/  

[http://stackoverflow.com/questions/42928979/event-hiding-on-dragging-to-parent-view-in-angular-bootstrap-calendar](url)

**Comment by gerome0123** [comment]
is there any solve this???
