### ISSUE TITLE
getBoundingClientRect in hitTest doesn't account for scrolled page

### ISSUE THREAD

**Issue by mattgoldspink** [fatlinesofcode/ngDraggable#112]
Hi,

I noticed after upgrading to 0.1.3 today that the following commit breaks the drop detection logic because getBoundClientRect doesn't account for the scroll position of a page:

https://github.com/fatlinesofcode/ngDraggable/commit/33de6ef506ff301ac3929a6fca8a598c299172f8#diff-045be7ab7709e1d9df374e76bac2659c

As per the definition from MDN:

"The Element.getBoundingClientRect() method returns the size of an element and its position relative to the viewport."

Whereas the comparison is against x/y positions relative to the document. The best way to reproduce this is to shrink your browser on this example and drag over drop area 1: http://htmlpreview.github.io/?https://github.com/fatlinesofcode/ngDraggable/blob/master/example.html

![image](https://cloud.githubusercontent.com/assets/415690/6769821/91fbcfcc-d0a1-11e4-82d7-052c87ff65c9.png)

As shown in the image due to the miscalculation Drop Area 2 is highlighted.

**Comment by josephlavin** [comment]
I am experiencing the same issue on my project.

@mattgoldspink: I found some issues while trying your commit. Looks like lines 15-23 start with `-`.  Also  referencing `$window` without passing it in via. dependency injection.
