### ISSUE TITLE
Doesnot give me the positions on drag complete

### ISSUE THREAD

**Issue by sprakashg** [fatlinesofcode/ngDraggable#113]
Hi Team, 
Im using this plugin for my site where there are thousands of records where user can drag and drop in a array, I followed your demo and built it, but the problem is when drag ends, I need to capture the latest dragged item position in a array, how do I do it?? example : have an array [1,2,3] when I Move 1 and 3 , I want the positions only of 1 and 3 which is been moved, not the complete array Please help me

**Comment by fatlinesofcode** [comment]
The positions are broadcast in the draggable:end event. Have you tried adding an event listener for that?

https://github.com/fatlinesofcode/ngDraggable/blob/master/ngDraggable.js#L190
