### ISSUE TITLE
Not working with touch devices

### ISSUE THREAD

**Issue by Sergey121** [fatlinesofcode/ngDraggable#119]
I try to use this code and it working fine. But then I use touch devices, it is not working, if my page include jQuery. If i don't use jQuery it is working fine. Can you help?
Thanks!

**Comment by vargavince91** [comment]
Just had the same problem right now. Add the jQuery after the angular.js.
```
<script src="bower_components/angular/angular.js"></script>
<script src="bower_components/jquery/dist/jquery.js"></script>
<script src="bower_components/ngDraggable/ngDraggable.js"></script>
```

@Sergey121

**Comment by Sergey121** [comment]
I added jQuery after angular.js but it doesn't work for me. Maybe because I have more other libraries? 
I think it is a bug (that I need include jQuery after angular. What if I don't want to use jQuery Lite and want to use full jQuery) and need to try to fix it.

**Comment by smusick-intego** [comment]
I'd agree with Sergey121 that this is a bug. Switching to JQLite broke more things that it fixed in my particular case. 
Does anyone know any details about why this fixes it? Does this library only work with JQLite or is there something else going on?

**Comment by fatlinesofcode** [comment]
You can still use the older version which uses jquery https://github.com/fatlinesofcode/ngDraggable/releases/tag/0.0.2

**Comment by smusick-intego** [comment]
Thanks, that's very much appreciated. That release appears to be before the dragScroll directive was implemented, but that it seemed to go back in without any problems.

**Comment by mfagadar** [comment]
I had to resort to the same approach described by @vargavince91. I use yeoman, bower and grunt for my project and I had to modify the order of `angular.js` and `jquery.js` under the bower.js section of my `index.html` file. 

The problem I have encountered is that every time I run `grunt serve` it switches them back to the original order, with jquery.js coming first in the list. Do you guys have any ideas on how to prevent this behavior ? I would be good not to have to switch the order of angular and jquery in the first place ...

**Comment by parliament718** [comment]
@vargavince91  worked like a charm for me, thanks.

**Comment by vargavince91** [comment]
@parliament718 Probably not related, but why do you need a clone?

**Comment by parliament718** [comment]
@vargavince91 I need the clone because I need to drag from one container into another, while both containers have overflow:hidden. So the clone is placed outside both of them. 

But yeah I know it's unrelated I was just saying that both bugs are fixed simulatenously when including jquery before. That is, the clone alignment is perfect and touch support is restored, but the rest of my app goes haywire.

**Comment by altsanz** [comment]
It says jQuery is needed (for example, ng-drag-handle won't work as it uses find() with attributes, and JQlite is limited to tags), but once I've imported jQuery it stops working on Android.
