### ISSUE TITLE
Clickable tags/inputs inside draggable

### ISSUE THREAD

**Issue by richardklotz** [fatlinesofcode/ngDraggable#12]
I would like to include "Clickable" objects inside the draggable. I got this to work adding this to the onpress event.  

if (evt.target.type === 'button' || evt.target.type === 'INPUT' || evt.target.tagName === 'A') return;

**Comment by alignsoft** [comment]
I ran into this issue using form fields on a draggable div, and the solution (at least in my case) was to attach ng-click="enterField()" to the input field, give it an id="enterField", and then include a function in the controller

		function enterField() {
			var inputTarget = document.getElementById("enterField");
			inputTarget.focus();
		}

This works with everyone except popup fields, for which I did this:

		function popUnitsSelectMenu() {
			var event = new MouseEvent('mousedown');
			var menu = document.getElementById("selectUnits");
			menu.dispatchEvent(event);
		}
This effectively creates a mousedown event and sends it to the dropdown field as though you'd clicked it manually, after which it behaves normally for the user.

This works on mobile.

I would love for their to be a support way to either target the elements that can be used to drag the container, or identify the elements in the container that should ignore the drag events and behave as normal without requiring the above code.
