### ISSUE TITLE
ng-drag-handle

### ISSUE THREAD

**Issue by leefernandes** [fatlinesofcode/ngDraggable#122]
Should the element.find('[ng-drag-handle']) brackets be there?

https://github.com/fatlinesofcode/ngDraggable/blob/master/ngDraggable.js#L46

**Comment by paschty** [comment]
I cannot find any documentation to ng-drag-handle, so it is not specified.
It finds all Elements ng-drag-handle as attribute.
If you would remove the brackets, it finds `<ng-drag-handle>` elements.
