### ISSUE TITLE
Not working on (some?) chrome browsers

### ISSUE THREAD

**Issue by aarmora** [fatlinesofcode/ngDraggable#125]
I know this sounds weird but I've done a lot of testing.  The example at http://htmlpreview.github.io/?https://github.com/fatlinesofcode/ngDraggable/blob/master/example.html will not work on my chrome browser (incognito or normal) but will work on firefox.  The same happens with my code, even in a fresh app with the bare essentials.

It looks like it acts differently in different browsers.

**Comment by gabn88** [comment]
Do other drag and drop actions (from other libraries) work? Because I sometimes have in my Ubuntu virtual machine that drag and drop does not work at all on chrome (regardles of the library or native html5). If so, I think it would be helpfull to give more information about your chrome version.

**Comment by aarmora** [comment]
It does appear that other drag and drop libraries are functioning.  I'm using Chrome Version 41.0.2272.118 m.  I just updated and it says I'm up to date.  Thanks for taking the time to look at this.

**Comment by Cinetik** [comment]
Works for me on Chrome Version 41.0.2272.89 (64-bit) - Ubuntu 14.04

**Comment by gabn88** [comment]
Seems to be an isolated issue. Are you sure you added jquery after AngularJS (see https://github.com/fatlinesofcode/ngDraggable/issues/121)?

**Comment by Cinetik** [comment]
ping @aarmora

**Comment by aarmora** [comment]
I haven't tested the order of jquery and angular, I will on Monday and get back to you.

I tried on several computers (both mine and others) with mixed results.  Some it worked fine for others it didn't work at all.

I'll try to get some better information for you.

Thanks!

Jordan

**Comment by aarmora** [comment]
It's not related to my js load order, as http://htmlpreview.github.io/?https://github.com/fatlinesofcode/ngDraggable/blob/master/example.html doesn't work for me normally or in incognito.  In windows 8 mode it does work as well as on firefox.  Anything else I could do to debug it?

**Comment by aarmora** [comment]
Okay, so I'm starting to suspect it has something to do with my laptop's touch screen software.  If I try to use my finger on my laptop monitor, I can drag it.  I guess this issue is more of a heads up than anything else.  It just seems that my touchscreen software + chrome (it works fine on firefox) clashes with it.

**Comment by Cinetik** [comment]
That could be the cause indeed Do you have any accessibility software/extension installed on your computer or Chrome ? Some works in incognito mode if you have explicitly enabled them. Make sure everything is disabled because the demo you linked works great for me on Chrome 41, Firefox 37 (both Ubuntu 14.04)

**Comment by francoisgrogor** [comment]
I am also experiencing issues when it comes to touch screen laptops. It seems as if both the click and touch events are firing. Still investigating. Has anyone else come across such issues?
