### ISSUE TITLE
ngCancelDrag no longer working

### ISSUE THREAD

**Issue by mattgoldspink** [fatlinesofcode/ngDraggable#126]
It looks like removing the call to isClickableElement breaks it in this commit:

https://github.com/fatlinesofcode/ngDraggable/commit/51fd11f0da58a693305fb70a71382260f0dd5a6f

**Comment by fatlinesofcode** [comment]
@ensign-rbaker why did you remove this?

**Comment by ryantehbaker** [comment]
it was causing the initial issue where simply clicking on a draggable item would start the drag events. imo, the drag events should start after mousedown -> mousemove. the presence of ngClick/ngDblClick should not stop an element from dragging (it creates confusion and more issues)

This is probably why test cases are needed, but my solution was to fix the issue of the drag events starting onclick. the ng-cancel-drag check should be moved to a separate function. 

my bad for not catching that in the first place though.

**Comment by mattgoldspink** [comment]
Maybe the right solution is to only check for ngCancelDrag here and not ngClick or ngDoubleClick. I agree with Ryans point that drag events should start on mouse move.



—

**Comment by fatlinesofcode** [comment]
fixed in latest

**Comment by ryantehbaker** [comment]
this only fixes the ng-cancel-drag issue. since ng-click and ng-dbl-click are still in isClickableElement, it stops the element from being dragged just because it has a click event on it. What is the reasoning behind this?

**Comment by fatlinesofcode** [comment]
there's not, https://github.com/fatlinesofcode/ngDraggable/blob/master/ngDraggable.js#L89

**Comment by ryantehbaker** [comment]
awesome! thanks for your work on this
