### ISSUE TITLE
not working on touch screen

### ISSUE THREAD

**Issue by systembugtj** [fatlinesofcode/ngDraggable#146]
I have try it on my lenovo Y10 which has a touch screen.

But the sample didn't work with touch

http://htmlpreview.github.io/?https://github.com/fatlinesofcode/ngDraggable/blob/master/example.html

**Comment by fatlinesofcode** [comment]
We're using a standard approach for detecting touch. Your device might pass that check.
https://github.com/fatlinesofcode/ngDraggable/blob/master/ngDraggable.js#L21

**Comment by systembugtj** [comment]
Yes, I can see it pass on my device. And I can see the touchstart event is fired on IE and Chrom.

Any idea why it won't response?

**Comment by systembugtj** [comment]
Just finally figure out, the reason is not caused by lib, on IE, it has default touch behavior which will cause touchmove event not fire to the object. So as IE side, you need to use  -ms-touch-action: none in css to disable the IE behavior, then everything works perfect.
