### ISSUE TITLE
if draggable element has any input control.. input control is not clickable 

### ISSUE THREAD

**Issue by ninjacms** [fatlinesofcode/ngDraggable#159]
Hi,
It is to inform you that there is an issue when you put text box ,checkbox or any control on draggable element (suppose DIV) the controls are not clickable because of  evt.preventDefault(); (Line 128).
The edit-ability is gone for any control on draggable element.  

Please look at this issue.

Thank you
Subhadip

**Comment by fatlinesofcode** [comment]
take a look ng-cancel-drag. There is an example in the readme.
