### ISSUE TITLE
push package to npm

### ISSUE THREAD

**Issue by tuchk4** [fatlinesofcode/ngDraggable#171]

**Comment by abhishekisnot** [comment]
+1

**Comment by fatlinesofcode** [comment]
its in bower, no plans to add to npm

**Comment by josephlavin** [comment]
In case anyone wants to use browserify and wants to use this... here is what I did:

Create a js file that requires the the source `ngDraggable.js` file and exports the string 'ngDraggable':

`./ngDraggable.js`:
~~~javascript
require('./bower_components/ngDraggable/ngDraggable.js');
module.exports = 'ngDraggable';
~~~

Then you can require that file when setting up angular:

~~~javascript
var angular = require('angular');
var app = angular.module('example', [
    require('./ngDraggable.js')
]);
~~~

**Comment by apalchys** [comment]
Hi @josephlavin , what do you think about adding package.json to the repository. It will give possibility to install ngDraggable directly from github?

**Comment by tuchk4** [comment]
@apalchys @josephlavin +100500

**Comment by thisispaul** [comment]
This would be very useful!

**Comment by AymanNatsheh** [comment]
+1

**Comment by toutpt** [comment]
Why don't you want to release it on npm ?

Oh someone has done it https://www.npmjs.com/package/ng-draggable
'@devup' so you can contact him if you are not agree.

I'm sad to learn this is not an official release....
