### ISSUE TITLE
Bower library is out of date

### ISSUE THREAD

**Issue by n370** [fatlinesofcode/ngDraggable#191]
Can we get @rustico fixes (d31a7a378cc3a70b6a1b7056ea521da9a59e70ab) in the registry version?

Thanks @fatlinesofcode, amazing work!!

**Comment by t8g** [comment]
+1

**Comment by jeroentradecast** [comment]
+1

**Comment by davemecha** [comment]
+1

**Comment by fatlinesofcode** [comment]
done
