### ISSUE TITLE
ISC or MIT license?

### ISSUE THREAD

**Issue by maruilian11** [fatlinesofcode/ngDraggable#241]
hi, recently we want to add your lib on https://cdnjs.com, i saw MIT license on github repo but ISC license on npm package.json, just want to confirm this with you.
thank you very much.

https://github.com/cdnjs/cdnjs/issues/7471
https://github.com/cdnjs/cdnjs/pull/7672

**Comment by fatlinesofcode** [comment]
https://www.npmjs.com/package/ngdraggable
