### ISSUE TITLE
official npm package?

### ISSUE THREAD

**Issue by maruilian11** [fatlinesofcode/ngDraggable#251]
hi, recently we want to add your lib to https://cdnjs.com, i want to confirm if this [lib](https://www.npmjs.com/package/ng-draggable) is your official npm package?
because it only has one version.

https://github.com/cdnjs/cdnjs/pull/7672#issuecomment-223799212
https://github.com/cdnjs/cdnjs/issues/7471

**Comment by fatlinesofcode** [comment]
just added, thanks, https://www.npmjs.com/package/ngdraggable
