### ISSUE TITLE
installing plugin via Bower gives me a different version

### ISSUE THREAD

**Issue by hubnelson** [fatlinesofcode/ngDraggable#254]
Hi,

I tried your plugin in my project and noticed that the drag and drop was not working in a smartphone, and then after some investigation, I realized that the version you have in github has that fixed. I then looked into the file and the ngDraggable.js I have in my /bower_components/ was different than the one that is in github. I tried several combination in my bower.json file,, also deleting bower cache, but none of them installed the version you have in github.
The file I get has 602 lines of code and the one that is in github has more. 
Has any one experienced something similar?

Thanks in advance,
Nelson

**Comment by csumudu** [comment]
i am also experiencing the same bower installed version is missing onDragStartCallback,onDragStopCallback callbacks

**Comment by fatlinesofcode** [comment]
version has been updated to the git master
