### ISSUE TITLE
How do I get the mouse location on drag start and drop?

### ISSUE THREAD

**Issue by derfsubterfuge** [fatlinesofcode/ngDraggable#33]
Currently I am doing something like:

<div ng-drop-success="afterMove($data,$event) ng-drop="true" />

<div ng-drag-success="beforeMove($data,$event) ng-drag="true" />

$scope.afterMove = function(item, event) {
    console.log('afterMove:',event);
}

$scope.beforeMove = function(item, event) {
    console.log('beforeMove:',event);
}

The events are objects and not events though.  They do not contain event.clientX or event.clientY or anything like that.  How do I get the drag start and drop end location?

**Comment by yashikagarg13** [comment]
@fatlinesofcode  I am accessing eventObj.event in ng-drop-success but unfortunately it is pointing to dragged element rather drop area.
