### ISSUE TITLE
click != drag

### ISSUE THREAD

**Issue by dboundz** [fatlinesofcode/ngDraggable#39]
The click event should not trigger the drag event. I should be able to have a div which is clickable but also draggable. See Trello as a good example of this. 

The only option I've been able to find is adding a nested, clickable element within a draggable div. This is a much less than desirable UX and rather unintuitive.

**Comment by Ulterior** [comment]
There is a bug by calling a callback on release: 

this -> doesnt call the callback
$rootScope.$broadcast('draggable:end', {x:_mx, y:_my, tx:_tx, ty:_ty, event:evt, element:element, data:_data, callback:onDragComplete, uid: _myid});

And this --> does

$rootScope.$broadcast('draggable:end', {x:_mx, y:_my, tx:_tx, ty:_ty, event:evt, element:element, data:_data, callback:onDragComplete});

additional parameter uid: _myid is the problem

**Comment by francoisgrogor** [comment]
I don't believe this should be closed. I believe the original issue is that an element should be draggable and clickable. (Not nested elements).

I am facing the same issue now. I have elements that can be dragged to a location. These very same elements has a click action associated to them. (Click to display additional behavior).

**Comment by DaWaD3** [comment]
Like @rancoisgrogor already said, this ticket should not be closed because the original issue is not solved.

I have found a lot of solutions with nested elements but I need the same element to be clickable and draggable. 

Is there any way or could it be fixed?

**Comment by bennettstuart** [comment]
Upon clicking my draggables, only the drop event fires, no drag event.
Using drop event I was able to check whether the object being "dropped" was previously dragged, or if it should be treated as clicked instead.
