### ISSUE TITLE
drag-over work incorrect with multiple drop zones

### ISSUE THREAD

**Issue by alexanderpa** [fatlinesofcode/ngDraggable#54]
Hello,

'drag-over' class appear only if draggable object over the last drop zone.

It reproduces in your example http://htmlpreview.github.io/?https://github.com/fatlinesofcode/ngDraggable/blob/master/example.html . If draggable object over drop area 2 'drag-over' class is appear, otherwise it doesn't.

**Comment by fatlinesofcode** [comment]
fixed in latest
