### ISSUE TITLE
ng-cancel-drag inheritance

### ISSUE THREAD

**Issue by irongomme** [fatlinesofcode/ngDraggable#57]
I've got dynamic contents inside my draggable elements, and i don't want them to be an anchor for drags ... is it natively possible , or does it need an enhancement to propagate ng-cancel-drag to their child html tags ?

**Comment by fatlinesofcode** [comment]
It should propagate to all child elements via this code in the ngCancelDrag directive

```
element.find('*').attr('ng-cancel-drag', 'ng-cancel-drag');
```
