### ISSUE TITLE
Module name doesn't match documented module name

### ISSUE THREAD

**Issue by ryanfields** [fatlinesofcode/ngDraggable#60]
I had to use ```angular-draggable``` in my dependency list instead of ```ngDraggable``` as suggested by the README.

```
angular.module('app', [ 'angular-draggable' ])
```

**Comment by fatlinesofcode** [comment]
do you have a fiddle example of the issue?

**Comment by durancristhian** [comment]
Something similar here, but I've fixed the "issue" (Really it's not an issue, I think)

In my case, I had the following markup

```
<div class="task" ng-repeat="task in column.tasks" 
		ng-drag="true" ng-drag-data="{task}" 
		ng-drag-success="onDragComplete($data, $event)" 
		ng-center-anchor="true">
	{{task.title}}
</div>
```

And I had an error on the console, but removing the **{ }** for the **ng-drag-data** all it's ok.
