### ISSUE TITLE
Error on mobile dragging

### ISSUE THREAD

**Issue by vinilanzoni** [fatlinesofcode/ngDraggable#65]
When I was testing on touch devices, drag do not works. Then I try to debug and on console is show the following error: 
[Error] TypeError: undefined is not an object (evaluating 'evt.touches[0]')
	onlongpress (ngDraggable.js, line 118)
	(anonymous function) (ngDraggable.js, line 95)
Is there any solution?

**Comment by vinilanzoni** [comment]
Additional information:
the touches array in evt doesn't exist on evt. Is there anything I have to do to make this array appear?

**Comment by fatlinesofcode** [comment]
just merged in a PR, that i think will fix this. Let us know how it goes.

**Comment by vinilanzoni** [comment]
Perfect! It works smoothly. Thanks!
