### ISSUE TITLE
Add ngDragMove callback

### ISSUE THREAD

**Issue by dvisockas** [fatlinesofcode/ngDraggable#66]
I have downloaded this plugin (awesome job, btw) and added ngDragMove callback. I believe this should be in the plugin. Can I submit a PR for that?

**Comment by fatlinesofcode** [comment]
Why do you need a callback? you can listen to this event, 'draggable:move'

**Comment by jkarttunen** [comment]
Maybe add events to documentation then :)

**Comment by dvisockas** [comment]
Yeah. If it is there but no one knows about it, is it usefull to have that? :)
