### ISSUE TITLE
dragged element visually constrained to scrollable container

### ISSUE THREAD

**Issue by jfspencer** [fatlinesofcode/ngDraggable#68]
There appears to be an issue when dragging an element within a scrollable container. Here is an example http://codepen.io/jfspencer/pen/jEPGGm . When actively dragging, the element is constrained to its originating scroll region. hovering over the right and left swipe panels registers with the plugin but the UI element is not visible. 

I have tried forcing an absolute position with the .dragging class and setting a high z-index.

side note: touch delay is set to 500ms.

**Comment by jfspencer** [comment]
This is a non-issue. -> Use clone feature and define cloned element outside the scrollable container. works perfectly.

**Comment by ricn** [comment]
I'm having the same problem. Can you please explain more in detail what you mean by using the clone feature for this?

**Comment by jfspencer** [comment]
@ricn In my case I needed draggable elements that were buried within a couple directive layers to be moved between the outer directive instances. 

The element to be dragged was setup normally, with ng-drag, ng-drag-data ng-drag-success etc.

The cloned element is placed in line with the outermost directive like this.

    <element>
        <innerElement>
            <draggableElement>
        </innerElement>
    </element>
    <draggableClone>
Since the clone is outside the bounds of draggable element's container, it is freely movable.

 I used the below css to hide the original dragging element.

    [ng-drag].dragging {
        opacity: 0;
    }

**Comment by ricn** [comment]
Thanks, I will look at it!
