### ISSUE TITLE
Inverted element position in Scrollable Element

### ISSUE THREAD

**Issue by jfspencer** [fatlinesofcode/ngDraggable#69]
When dragging an element within a scrollable container the dragged elements position is inverted in relation to scroll offset. see an example here : 

side note : touch delay set to 500ms

**Comment by jfspencer** [comment]
This issue is resolvable using the clone directive and css adjustments. non-issue.

**Comment by rmithun** [comment]
@jfspencer  How you solved this issue? Could you please brief it?
