### ISSUE TITLE
Does not work with matrix3d on parent

### ISSUE THREAD

**Issue by janober** [fatlinesofcode/ngDraggable#73]
When the parent element has a matrix3d transformation on it, everything gets messed up and module is unusable.

Very basic example here:
http://codepen.io/anon/pen/dPWWZB

**Comment by janober** [comment]
I am unable to get it working. Changing the "moveElement" to also use matrix3d helps to fix it partly (at least the display issues I have on my chromium) however have no luck with the main issue, the offest. Do not find a way to get the initial-position of the div to attach it properly to the mouse.

Anybody any idea where that value could be? Because I can not find it anywhere.

**Comment by fatlinesofcode** [comment]
The offset code is located in the service function ngDraggable:: getPrivOffset

**Comment by janober** [comment]
Thanks a lot! That helped and could now fix it. Created a pull-request.
