### ISSUE TITLE
Clone way: the source element disappear, what's the key points?

### ISSUE THREAD

**Issue by yianpuodiaotu** [fatlinesofcode/ngDraggable#75]
I used this directive in a clone way. when i dragging the element, the source element disappear, what's the  key points? any suggests  will be appreciated.

**Comment by Philzen** [comment]
Experiencing the same problem here, unable to make my application clone the draggable's content. Though, at the same time, it can see *both* the original element *and* the `ng-drag-clone` element being modified and moved in sync when observing the html structure in dev tools.

**Comment by Philzen** [comment]
OK, i got it working by rigorously following the structure in the demo (including CSS), which for my understanding requires a few too many hardcoded elements, i am wondering whether the angular module wouldn't be able to render them a needed (i.e. css properties, the drag-clone-element, and the extra wrapper `.drag-object` containing `ng-drag` - though the wrapper itself is being moved).

**Comment by Philzen** [comment]
@fatlinesofcode Closing an issue report w/o any comment whatsoever does neither come across very helpful in regards to yianpuodiaotu's problem, nor does it make my feedback worthwhile. Or is there something in the making, respectively did i miss something?
