### ISSUE TITLE
onrelease has a bug in callback

### ISSUE THREAD

**Issue by Ulterior** [fatlinesofcode/ngDraggable#83]
There is a bug by calling a callback on release:

this -> doesnt call the callback
$rootScope.$broadcast('draggable:end', {x:_mx, y:_my, tx:_tx, ty:_ty, event:evt, element:element, data:_data, callback:onDragComplete, uid: _myid});

And this --> does

$rootScope.$broadcast('draggable:end', {x:_mx, y:_my, tx:_tx, ty:_ty, event:evt, element:element, data:_data, callback:onDragComplete});

Applies in case of simple click on the draggable element
additional parameter uid: _myid is the problem

**Comment by fatlinesofcode** [comment]
fixed in latest
