### ISSUE TITLE
bower install defaults to old version 0.0.31

### ISSUE THREAD

**Issue by Sb87** [fatlinesofcode/ngDraggable#84]
Bower believes the latest version of ngDraggable is 0.0.31 instead of 0.0.4. This will be a problem for all releases before 0.0.32 as well. The solution, I assume, would be to relabel version 0.0.31 to 0.0.3.1 (note the extra dot), or change 3 to 4 and 4 to 5.

**Comment by luisrudge** [comment]
Yeah. I had that problem too

**Comment by fatlinesofcode** [comment]
fixed, thanks

**Comment by Sb87** [comment]
Bower still reports the following versions:

> Available versions:
>   - 0.0.31
>   - 0.0.4
>   - 0.0.3

I think you need to unregister version 0.0.31: http://bower.io/docs/creating-packages/#unregister

**Comment by fatlinesofcode** [comment]
Well that was bad idea as I wasn't able to re-register it under same name. Bower no longer accepts camelcase. Package is now known as 'ngdraggable'
