### ISSUE TITLE
Adding a touch-event

### ISSUE THREAD

**Issue by tempflip** [fatlinesofcode/ngDraggable#85]
Hi All,

we are using ngDraggable in our project, and were needed a specific 'touch' event, which is triggered when a dragged element is hovering over a droppable element. I am aware that there is an ngDragMove event on the ngDrop directive, however, it is fired all the time when an element is moved, so that's not exactly what we needed.

We've came up with a possible solution.
In HTML:
``` <div ng-drop="true" ng-drop-success="columnDropped($data, $event)" ng-touching-action="touched()" />```

In the ngDrop directive : 
```javascript
    var onTouchAction = $parse(attrs.ngTouchingAction);

.
.
.
                    var isTouching = function(mouseX, mouseY, dragElement) {
                        var touching= hitTest(mouseX, mouseY);
                        updateDragStyles(touching, dragElement);
                        //*** added by peter***
                        fireTouchingAction(touching, dragElement);
                        ///
                        return touching;
                    }

.
.
.
                    var fireTouchingAction = function(touching, dragElement) {
                        if(touching){
                            if (attrs.ngTouchingAction != undefined) {
                                onTouchAction(scope);
                            }
                        }
                    }
```

What do you think about this solution? Any better ideas? Maybe something similar could be implemented in the future?

thanks!

**Comment by fatlinesofcode** [comment]
I've added a scope variable within ngDrop. You should be able to bind or watch that.
