### ISSUE TITLE
ng-drag-start doesn't work

### ISSUE THREAD

**Issue by fhrtms** [fatlinesofcode/ngDraggable#89]
Hi @all,

The drag and drop functionality works, but  the drag-start event is not fired on drag start.

The html:

```html
<md-item ng-repeat="item in items" ng-drag-start="onDragStart(item)" ng-drag="true" ng-drag-data="item">
```

The function in my Controller:

```javascript
        $scope.onDragStart = function(item){
            console.log(item);
        }
```

**Comment by dchahla** [comment]
+1

**Comment by gspinella** [comment]
+2

**Comment by dchahla** [comment]
@gspinella my solution was to just use ionic's on-drag..... on-drag= "onDragStart($data, $event)" and handled everything I wanted to in the controller

**Comment by fatlinesofcode** [comment]
ngDragStart should be used on a ng-drop element

**Comment by parliament718** [comment]
Having ngDragStart on the dropable element doesn't really make sense, but in any case, it doesn't work there either.

I was able to accomplish what I needed with ``` ng-mousedown="onDragStart($data, $event)" ```

In my case I wanted to copy the element html into the clone so that it appears the same:

```
$scope.onDragStart = function ($data, $event) {
            var clone = angular.element($event.currentTarget).clone();
            angular.element("[ng-drag-clone]").html(clone);
        };
```

**Comment by aaronmallen** [comment]
:+1:

**Comment by spbrien** [comment]
+1

**Comment by applee** [comment]
+1

**Comment by dtelaroli** [comment]
+1

**Comment by mdopieralski** [comment]
+1

**Comment by scantineau** [comment]
Works with the last version on GitHub !
I don't know why but bower update doesn't seem to update correctly the package... Try to replace full code with copy/paste and it will works !

**Comment by jdnichollsc** [comment]
Any codepen of example? 👍

**Comment by gerome0123** [comment]
is this issue fix?
