### ISSUE TITLE
Item positioned too much to the right while dragging in combination with angular material design right sidenav

### ISSUE THREAD

**Issue by lievenjanssen** [fatlinesofcode/ngDraggable#92]
If you drag the item it falls off the screen if you move your cursor to the middle of the screen the item will appear.

Example: http://plnkr.co/edit/EHC9zC?p=preview

**Comment by lievenjanssen** [comment]
hey @fatlinesofcode  were you able to check this out yet?

**Comment by fatlinesofcode** [comment]
looks like you're using an old version. latest used css transforms for positioning

**Comment by durga598** [comment]
[Example](http://jsfiddle.net/durga598/qo1gmrrr/286/)
If you drag an div from angular material sidenav that item is not coming up as like normal div whether we give a z-index of 99999. Any solution for this?
