### ISSUE TITLE
trigger drag from a button and leave elements where they are

### ISSUE THREAD

**Issue by luisrudge** [fatlinesofcode/ngDraggable#97]
Hey. I want to use this lib, but I need the drag to only start when I'm clicking an specific button. Also, it need's to let the elements where they are. Makes no sense to push the elements to the right or to the left

![ngdraggable](https://cloud.githubusercontent.com/assets/941075/6424385/0784b8b2-bed7-11e4-9f13-89d848d56dae.gif)

**Comment by fatlinesofcode** [comment]
have a look at ng-cancel-drag

**Comment by luisrudge** [comment]
I don't want to cancel the drag. I want it not to go right or left

**Comment by fatlinesofcode** [comment]
You'll need to modify the moveElement function like this : 
```
var moveElement = function (x, y) {
x=0; // override
                        element.css({
                            transform: 'matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, '+x+', '+y+', 0, 1)','z-index': 99999,
                            '-webkit-transform': 'matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, '+x+', '+y+', 0, 1)'
                            //,margin: '0'  don't monkey with the margin,
                        });
                    }

**Comment by luisrudge** [comment]
Thanks!
