### ISSUE TITLE
ngPreventDrag may be broken

### ISSUE THREAD

**Issue by martinth** [fatlinesofcode/ngDraggable#98]
I'm not really sure about it, but at least for me (Chrome 41) the `ngPreventDrag` throws an error. 

The culprit is in [line 425](https://github.com/fatlinesofcode/ngDraggable/blob/master/ngDraggable.js#L425). `event.originalEvent` is accessed but for me `e` already is the original event. Simply removing the line and changed all `e` to `event` fixes the issue for me but I'm not sure if this just a Chrome thing...

**Comment by fatlinesofcode** [comment]
thanks, fixed in latest.
